//GET ALL
GET http://localhost:3000/estoque

###
POST http://localhost:3000/produto
Content-Type: application/json

{
    "nome": "Mouse",
    "descricao": "Logitech G709",
    "valor": "50000",
    "quantidade": 500
}

###
DELETE http://localhost:3000/produto/6

###
PATCH http://localhost:3000/estoque/dim/1
Content-Type: application/json

{
    "quantidade": 450
}
